export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAILURE = 'TASKS_FAILURE';
export const TASKS_FILTER = 'TASKS_FILTER';
export const TASKS_SUCCESS_PUT = 'TASKS_SUCCESS_PUT';
export const TASKS_SUCCESS_POST = 'TASKS_SUCCESS_POST';